### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by pallzoltan**
Removed `IMT_ASSERT`.

### CODE REVIEW

**Comment by hvge** [comment]
Hi there! Sorry that I quite ignored your previous PR. I was preparing some comments on that change, but then suddenly a lot of work came on me, so I completely forgot to finish my review :(

But, this is a quite old piece of code, which I don't want to continue to maintain. If you want, I can move the repository ownership to you or to organization you work for.

**Comment by pallzoltan** [comment]
Actually I'm working on our copy, i sent this PR to yours accidentally .) I'll be maintaining the code over at `https://github.com/ma-myair/spayd-sdk-ios`

**Comment by hvge** [comment]
Ok then :)

**Comment by hvge** [comment]
I've at least updated readme, which points now to your repository.

**Comment by pallzoltan** [comment]
Thanks!

**Pull request closed without merging**
